import { Router } from 'express';
import { adminRouter } from '../../../modules/admin/presentation/admin.routes';
import { aiAssistantRouter } from '../../../modules/ai-assistant/presentation/ai-assistant.routes';
import { appointmentsRouter } from '../../../modules/appointments/presentation/appointments.routes';
import { authRouter } from '../../../modules/auth/presentation/auth.routes';
import { automationInstancesRouter } from '../../../modules/automation-instances/presentation/automation-instances.routes';
import { automationTemplatesRouter } from '../../../modules/automation-templates/presentation/automation-templates.routes';
import { catalogRouter } from '../../../modules/catalog/presentation/catalog.routes';
import { channelsRouter } from '../../../modules/channels/presentation/channels.routes';
import { executionsRouter } from '../../../modules/executions/presentation/executions.routes';
import { healthRouter } from '../../../modules/health/presentation/health.routes';
import { integrationsRouter } from '../../../modules/integrations/presentation/integrations.routes';
import { knowledgeRouter } from '../../../modules/knowledge/presentation/knowledge.routes';
import { ordersRouter } from '../../../modules/orders/presentation/orders.routes';
import { plansRouter } from '../../../modules/plans/presentation/plans.routes';
import { tenantsRouter } from '../../../modules/tenants/presentation/tenants.routes';
import { usageRouter } from '../../../modules/usage/presentation/usage.routes';
import { usersRouter } from '../../../modules/users/presentation/users.routes';
import { webhooksRouter } from '../../../modules/webhooks/presentation/webhooks.routes';

export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use(webhooksRouter);
apiRouter.use(authRouter);
apiRouter.use(usersRouter);
apiRouter.use(plansRouter);
apiRouter.use(tenantsRouter);
apiRouter.use(integrationsRouter);
apiRouter.use(channelsRouter);
apiRouter.use(catalogRouter);
apiRouter.use(knowledgeRouter);
apiRouter.use(appointmentsRouter);
apiRouter.use(ordersRouter);
apiRouter.use(aiAssistantRouter);
apiRouter.use(automationTemplatesRouter);
apiRouter.use(automationInstancesRouter);
apiRouter.use(usageRouter);
apiRouter.use(executionsRouter);
apiRouter.use(adminRouter);
